pascalberger/chocolatey-packages

- git-lfs-install/git-lfs.install.nuspec
- git-lfs-install/tools/ChocolateyInstall.ps1
- git-lfs/git-lfs.nuspec
> Add git-lfs 

- appveyor.yml
> Add build script

- git-lfs-install/git-lfs.install.nuspec
Fix packageSourceUrl in git-lfs.install package
> Fix packageSourceUrl

- git-lfs-install/git-lfs.install.nuspec
- git-lfs/git-lfs.nuspec
Fix author to avoid having Chocolatey split it to two and be conform with other packages
> Fix author for GitHub

- git-lfs-install/git-lfs.install.nuspec
Add dependency to Git package to then git-lfs.install Package
Fixes #5
> Add dependency to Git package to git-lfs.install.

- git-lfs-install/git-lfs.install.nuspec
- git-lfs/git-lfs.nuspec
> Review fixes

- typescript/tools/chocolateyInstall.ps1
- typescript/typescript.vs2013.nuspec
> Added typescript

- typescript/tools/chocolateyInstall.ps1
- typescript/typescript.vs2013.nuspec
> Update to Typescript 1.8.2

- sourcetree/SourceTree.nuspec
> SourceTree fixes

- visualstudiocode/VisualStudioCode.nuspec
- visualstudiocode/tools/ChocolateyInstall.ps1
- Update parameters to disable default features
- Update package description
> Update VisualStudioCode parameters

- visualstudiocode/VisualStudioCode.nuspec
Unless I'm missing something?
https://code.visualstudio.com/docs/supporting/requirements
> VSCode doesn't depend on .NET, that I can see

- automatic/git-lfs.install/git-lfs.install.nuspec
- automatic/git-lfs/git-lfs.nuspec
- automatic/sonarlint-vs2015/sonarlint-vs2015.nuspec
Add files explicitely to the manifest to avoid ending update.ps1 as part of the package
> Add files explicitely to the manifest

- appveyor.yml
Reverts pascalberger/chocolatey-packages#106
> Revert "Go back to release version of AU"

- appveyor.yml
- scripts/EventLogs.ps1
- scripts/README.md
- scripts/Set-DescriptionFromReadme.ps1
- scripts/Take-Screenshot.ps1
- scripts/Test-RepoPackage.ps1
- scripts/Update-ChangelogVersion.ps1
- scripts/Update-IconUrl.ps1
- scripts/Update-OnETagChanged.ps1
- scripts/au_extensions.psm1
- test_all.ps1
- update_all.ps1
> Update build script

- manual/vscode-autofilename/README.md
- manual/vscode-autofilename/update.ps1
- manual/vscode-autofilename/vscode-autofilename.nuspec
- manual/vscode-csharp/README.md
- manual/vscode-csharp/update.ps1
- manual/vscode-csharp/vscode-csharp.nuspec
- manual/vscode-docker/README.md
- manual/vscode-docker/update.ps1
- manual/vscode-docker/vscode-docker.nuspec
- manual/vscode-editorconfig/README.md
- manual/vscode-editorconfig/update.ps1
- manual/vscode-editorconfig/vscode-editorconfig.nuspec
- manual/vscode-jscslinting/README.md
- manual/vscode-jscslinting/update.ps1
- manual/vscode-jscslinting/vscode-jscslinting.nuspec
- manual/vscode-jshint/README.md
- manual/vscode-jshint/update.ps1
- manual/vscode-jshint/vscode-jshint.nuspec
- manual/vscode-mssql/README.md
- manual/vscode-mssql/update.ps1
- manual/vscode-mssql/vscode-mssql.nuspec
- manual/vscode-powershell/README.md
- manual/vscode-powershell/update.ps1
- manual/vscode-powershell/vscode-powershell.nuspec
- manual/vscode-tslint/README.md
- manual/vscode-tslint/update.ps1
- manual/vscode-tslint/vscode-tslint.nuspec
Add README, update dependency and metadata for Visual Studio Code extension packages
> (vscode-*) Add README, update dependency and metadata

- manual/vscode-autofilename/vscode-autofilename.nuspec
- manual/vscode-csharp/vscode-csharp.nuspec
- manual/vscode-docker/vscode-docker.nuspec
- manual/vscode-editorconfig/vscode-editorconfig.nuspec
- manual/vscode-jscslinting/vscode-jscslinting.nuspec
- manual/vscode-jshint/vscode-jshint.nuspec
- manual/vscode-mssql/vscode-mssql.nuspec
- manual/vscode-powershell/vscode-powershell.nuspec
- manual/vscode-tslint/vscode-tslint.nuspec
Bump version number for Visual Studio Code extension packages
> (vscode-*) Bump version number

- manual/vscode-autofilename/vscode-autofilename.nuspec
- manual/vscode-csharp/vscode-csharp.nuspec
- manual/vscode-docker/vscode-docker.nuspec
- manual/vscode-editorconfig/vscode-editorconfig.nuspec
- manual/vscode-jscslinting/vscode-jscslinting.nuspec
- manual/vscode-jshint/vscode-jshint.nuspec
- manual/vscode-mssql/vscode-mssql.nuspec
- manual/vscode-powershell/vscode-powershell.nuspec
- manual/vscode-tslint/vscode-tslint.nuspec
Exclude README and update script from package
> (vscode-*) Exclude README and update script from package

- automatic/coderush-vs2015/coderush-vs2015.nuspec
- manual/typescript/typescript.vs2013.nuspec
- manual/vscode-autofilename/README.md
- manual/vscode-autofilename/vscode-autofilename.nuspec
- manual/vscode-csharp/README.md
- manual/vscode-csharp/vscode-csharp.nuspec
- manual/vscode-docker/README.md
- manual/vscode-docker/vscode-docker.nuspec
- manual/vscode-editorconfig/README.md
- manual/vscode-editorconfig/vscode-editorconfig.nuspec
- manual/vscode-jscslinting/README.md
- manual/vscode-jscslinting/vscode-jscslinting.nuspec
- manual/vscode-jshint/README.md
- manual/vscode-jshint/vscode-jshint.nuspec
- manual/vscode-mssql/README.md
- manual/vscode-mssql/vscode-mssql.nuspec
- manual/vscode-powershell/README.md
- manual/vscode-powershell/vscode-powershell.nuspec
- manual/vscode-tslint/README.md
- manual/vscode-tslint/vscode-tslint.nuspec
- scripts/Update-IconUrl.ps1
Replace RawGit with jsDelivr as RawGit will shutdown its service
> (GH-121) Replace RawGit with jsDelivr

- scripts/Update-IconUrl.ps1
Fix icon update script to correct repository
> Fix icon update script

- .mergify.yml
Setup mergify to automatically delete PR branches
> Setup mergify to automatically delete PR branches

- automatic/coderush-vs2015/coderush-vs2015.nuspec
Fix icon url for coderush-vs2015 package
> (coderush-vs2015) Fix icon url

- manual/vscode-tslint/vscode-tslint.nuspec
Add note that extension will be uninstalled to description
> (vscode-tslint) Add note that extension will be uninstalled

- manual/vscode-tslint/README.md
- manual/vscode-tslint/vscode-tslint.nuspec
> (vscode-tslint) Update README

- manual/vscode-tslint/vscode-tslint.nuspec
> (vscode-tslint) Fix author

- scripts/Test-RepoPackage.ps1
- scripts/Update-IconUrl.ps1
- scripts/Update-PackageSourceUrl.ps1
- scripts/au_extensions.psm1
- test_all.ps1
- update_all.ps1
> Update build scripts

- appveyor.yml
> Update AppVeyor build script

- automatic/vscode-csharp/README.md
- automatic/vscode-csharp/legal/LICENSE.txt
- automatic/vscode-csharp/legal/VERIFICATION.txt
- automatic/vscode-csharp/tools/chocolateyInstall.ps1
- automatic/vscode-csharp/tools/chocolateyUninstall.ps1
- automatic/vscode-csharp/update.ps1
- automatic/vscode-csharp/vscode-csharp.nuspec
- manual/vscode-csharp/tools/ChocolateyInstall.ps1
- manual/vscode-csharp/tools/chocolateyUninstall.ps1
- manual/vscode-csharp/update.ps1
Embed VSIX and support installation to user level installations or insider builds
> (vscode-csharp) Embed VSIX

- automatic/vscode-mssql/README.md
- automatic/vscode-mssql/legal/LICENSE.txt
- automatic/vscode-mssql/legal/VERIFICATION.txt
- automatic/vscode-mssql/tools/chocolateyInstall.ps1
- automatic/vscode-mssql/tools/chocolateyUninstall.ps1
- automatic/vscode-mssql/update.ps1
- automatic/vscode-mssql/vscode-mssql.nuspec
- manual/vscode-mssql/tools/ChocolateyInstall.ps1
- manual/vscode-mssql/tools/chocolateyUninstall.ps1
- manual/vscode-mssql/update.ps1
Embed VSIX and add support for user level installations and insider builds.
> (vscode-mssql) Embed VSIX

- automatic/vscode-csharp/tools/chocolateyUninstall.ps1
Update extension ID for vscode-csharp package
> (vscode-csharp) Update extensionId

- automatic/vscode-csharp/vscode-csharp.nuspec
> (vscode-csharp) Fix package URLs

- automatic/vscode-csharp/tools/chocolateyInstall.ps1
- automatic/vscode-csharp/update.ps1
Fix parsing of release information for GitHub for Visual Studio Code C# extension
> Fix update of VSCode C# extension

- automatic/vscode-azurerepos/update.ps1
Fix parsing of release information for GitHub for Visual Studio Code Azure Repos extension
> Fix update of VSCode Azure Repos extension

- automatic/vscode-powershell/update.ps1
Fix parsing of release information for GitHub for Visual Studio Code PowerShell extension
> Fix update of VSCode PowerShell extension

- automatic/vscode-mssql/update.ps1
Fix parsing of release information for GitHub for Visual Studio Code MsSql extension
> Fix update of VSCode MsSql extension

- automatic/azuredatastudio-powershell/README.md
Update README for `azuredatastudio-powershell` with content from extension
> (azuredatastudio-powershell) Update README

- automatic/azuredatastudio-powershell/update.ps1
Fix parsing of release information for GitHub for Azure Data Studio Powershell extension
> (azuredatastudio-powershell) Fix update
